# Configuration for xFinder model
xfinder_model:
  model_name: "xFinder-llama38it"                       # must have, xFinder-qwen1505 or xFinder-llama38it
  model_path: "../xFinder-llama38it"  # path to the model, only need if use local deployment
  url: null                      # url to the model, only need if use remote deployment
data_path: "../Bastidas-Ponce-2019-all-outputs.json"                  # path to the data which need to be evaluated